// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_fQVhTN49ZPNaYghAoaRoBbJj0MCYRaM',
    appId: '1:818756248734:web:b5069c0dbac6d60d4a878f',
    messagingSenderId: '818756248734',
    projectId: 'talkathon-b1d2c',
    authDomain: 'talkathon-b1d2c.firebaseapp.com',
    storageBucket: 'talkathon-b1d2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7d7ZVZg2ZkmbJCd42uFUKiYjqfz_C_3s',
    appId: '1:818756248734:android:5219fb62e40e7c194a878f',
    messagingSenderId: '818756248734',
    projectId: 'talkathon-b1d2c',
    storageBucket: 'talkathon-b1d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkngcI0A_7b8XtRCwcSlk8c3RUU94C4MM',
    appId: '1:818756248734:ios:daf60eaca3ffc6654a878f',
    messagingSenderId: '818756248734',
    projectId: 'talkathon-b1d2c',
    storageBucket: 'talkathon-b1d2c.appspot.com',
    iosBundleId: 'com.example.talkathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkngcI0A_7b8XtRCwcSlk8c3RUU94C4MM',
    appId: '1:818756248734:ios:daf60eaca3ffc6654a878f',
    messagingSenderId: '818756248734',
    projectId: 'talkathon-b1d2c',
    storageBucket: 'talkathon-b1d2c.appspot.com',
    iosBundleId: 'com.example.talkathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_fQVhTN49ZPNaYghAoaRoBbJj0MCYRaM',
    appId: '1:818756248734:web:f23ad06b3bf616324a878f',
    messagingSenderId: '818756248734',
    projectId: 'talkathon-b1d2c',
    authDomain: 'talkathon-b1d2c.firebaseapp.com',
    storageBucket: 'talkathon-b1d2c.appspot.com',
  );
}
